spring.application.name=restaurante_spring


#Base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/restaurante_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Dialecto de la base de datos
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#Configuración de JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true